const SUCURSALES = [
  'Flores',
  'Mirasierra',
  'Satélite',
  'Benavides',
  'Seminario',
  'Torreón',
  'Parras',
  'Cardenas',
  'Ixtlero',
  'Centro',
];

const TIPOS_GASTO = [
  'Dentalmix (depósito dental interno)',
  'Insumos médicos externos',
  'Especialistas',
  'Laboratorio interno',
  'Laboratorio externo',
  'Comisiones manager global',
  'Comisiones doctores',
  'Comisiones recepción',
  'Renta local comercial',
  'Servicios (agua, luz, teléfono, internet)',
  'Pago celulares y saldo',
  'Gasolina y tag',
  'Limpieza',
  'Papelería y oficina',
  'Mantenimiento',
  'Mercadotecnia (agencias y saldo meta)',
  'Nómina/IMSS/ISN/ISR',
  'Nómina IMSS ISN e ISR de comisiones',
  'Nómina IMSS ISN e ISR administración',
  'Devolución a pacientes',
  'Renta de casas',
  'Tomox',
  'Servicio becario',
  'Comisiones bancarias',
  'Software odontológico',
  'Honorarios contables y timbres',
  'Software contable/administrativo',
  'Remodelación',
  'Trámites administrativos',
  'Servicios legales',
  'Finiquitos',
  'Otros',
];

// Meta mensual de ingreso fija por clinica (se aplica igual todos los meses).
const METAS_MENSUALES = {
  Flores: 579800,
  Mirasierra: 579800,
  Satélite: 403000,
  Benavides: 416000,
  Seminario: 403000,
  Torreón: 579800,
  Parras: 403000,
  Cardenas: 403000,
  Ixtlero: 390000,
  Centro: 390000,
};

module.exports = { SUCURSALES, TIPOS_GASTO, METAS_MENSUALES };
